apiVersion: v1
kind: ServiceAccount
metadata:
  name: server-ns

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: server-ns-read
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "watch", "list"]
    
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: server-ns-read-bind
subjects:
- kind: ServiceAccount
  name: server-ns
  namespace: production
roleRef:
  kind: Role
  name: server-ns-read
  apiGroup: rbac.authorization.k8s.io 
