apiVersion: apps/v1
kind: Deployment
metadata:
  name: "goserver"
  labels:
    app: "goserver"
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 2
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: "silasstofel/hello-go:v3.8"
          
#          livenessProbe:
#            httpGet:
#              path: /healthz
#              port: 8000
#            periodSeconds: 10
#            failureThreshold: 5
#            successThreshold: 1
#            timeoutSeconds: 2

          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 5
            failureThreshold: 1
            successThreshold: 1
            timeoutSeconds: 1
            initialDelaySeconds: 10    
                      
          envFrom:
            - configMapRef: 
                name: goserver-env
            - secretRef:
                name: goserver-secret    
          volumeMounts:
            - mountPath: "/go/heroes"
              name: conf-volume-heroes                
          #env:
          #  - name: NAME
          #    valueFrom:
          #      configMapKeyRef:
          #        name: goserver-env
          #        key: NAME
          #  - name: AGE
          #    valueFrom:
          #      configMapKeyRef:
          #        name: goserver-env
          #        key: AGE
      volumes:
        - name: conf-volume-heroes
          configMap:
            name: configmap-heroes
            items:
              - key: heroes
                path: "heroes.txt"
